kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  name: job-account-management
  labels:
    build: job-account-management
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'job-account-management:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-11-ubi8'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  runPolicy: Serial
